name: dart_protobuf_example
version: 0.0.1
description: example of using Protocol Buffers with Dart
author: john ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/dart_protobuf_example

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  protobuf: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
