name: protobuf_runner
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/dart-protobuf-runner

version: 1.0.0
description: Builds Dart protocol buffers.

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  args: ^0.13.7
  path: ^1.4.1

executables:
  pbuf: main